

!function(e){          
var a = window.webpackJsonp.push;
function b(x){    
 if (x[0][0]=="main_chart"){
  x[1]["+lbv"] =function(e) {
        e.exports = JSON.parse(
	'{"free0":{"CHART_STORAGE":{"limit":5},"MULTIPLE_CHARTS":{"limit":2},"CUSTOM_INTERVALS":{},"MULTIPLE_WATCHLISTS":{},"IMPORT_WATCHLISTS":{},"EXPORT_WATCHLISTS":{},"INDICATORS_ON_CHART":{"limit":5},"TV_VOLUMEBYPRICE":{"study_packages":["tv-volumebyprice"]},"STUDY_ON_STUDY":{"limit":270,"child_limit":1},"TICK_BY_TICK_PUSH_DATA":{},"SERVER_SIDE_ALERTS":{"limit":10},"SCREENER_ALERTS":{"limit":10},"SCREENER_AUTO_REFRESH":{},"SCREENER_EXPORT_DATA":{},"SCREENER_INTERVALS":{"interval":["1s","1m","5m","15m","1h","4h","6h","12h","1D","1W","1M"]},"SCREENER_REALTIME_IDC":{},"NO_SPONSORED_ADS":{},"STUDY_TEMPLATES":{"limit":99999},"SIMULTANEOUS_CONNECTIONS":{"limit":1},"IDC_AVAILABLE_DELAY":{},"STATUS":{"disable_on_trial":false},"BAR_REPLAY_INTRADAY":{},"MULTIFLAGGED_SYMBOLS_LISTS":{},"SHOWS":{"disable_on_trial":false},"ALERTS_WEBHOOK":{},"DEEP_FUNDAMENTALS_HISTORY":{}},'
		+		'"free1":{"CHART_STORAGE":{"limit":1},"MULTIPLE_CHARTS":{"limit":1},"INDICATORS_ON_CHARTx":{"limit":3},"STUDY_ON_STUDY":{"limit":270,"child_limit":1},"SERVER_SIDE_ALERTS":{"limit":1},"SCREENER_ALERTS":{"limit":1},"SCREENER_INTERVALS":{"interval":["1s","1m","5m","15m","1h","4h","6h","12h","1D","1W","1M"]},"STUDY_TEMPLATES":{"limit":1},"SIMULTANEOUS_CONNECTIONS":{"limit":1}},'
		+ 		'"__legacy_pro":{"CHART_STORAGE":{"limit":99999},"MULTIPLE_CHARTS":{"limit":8},"CUSTOM_INTERVALS":{},"MULTIPLE_WATCHLISTS":{},"IMPORT_WATCHLISTS":{},"EXPORT_WATCHLISTS":{},"INDICATORS_ON_CHART":{"limit":99999},"TV_VOLUMEBYPRICE":{"study_packages":["tv-volumebyprice"]},"STUDY_ON_STUDY":{"limit":270,"child_limit":99999},"TICK_BY_TICK_PUSH_DATA":{},"SERVER_SIDE_ALERTS":{"limit":10},"SCREENER_ALERTS":{"limit":10},"SCREENER_AUTO_REFRESH":{},"SCREENER_EXPORT_DATA":{},"SCREENER_INTERVALS":{"interval":["1s","1m","5m","15m","1h","4h","6h","12h","1D","1W","1M"]},"SCREENER_REALTIME_IDC":{},"NO_SPONSORED_ADS":{},"STUDY_TEMPLATES":{"limit":99999},"SIMULTANEOUS_CONNECTIONS":{"limit":1},"IDC_AVAILABLE_DELAY":{},"STATUS":{"disable_on_trial":false},"MULTIFLAGGED_SYMBOLS_LISTS":{},"BAR_REPLAY_INTRADAY":{},"SHOWS":{"disable_on_trial":false},"ALERTS_WEBHOOK":{},"DEEP_FUNDAMENTALS_HISTORY":{}},"__legacy_pro_realtime":{"extends":"__legacy_pro","TV_PROSTUDIES":{"study_packages":["tv-prostudies"]},"SERVER_SIDE_ALERTS":{"limit":1000},"SCREENER_ALERTS":{"limit":30},"CAN_EDIT_PUBLIC_CHATS":{"disable_on_trial":false},"EXPORT_CHART_DATA":{}},"__legacy_pro_premium":{"extends":"__legacy_pro_realtime","SCREENER_ALERTS":{"limit":100},"ALERTS_TRUE_SMS":{"disable_on_trial":false},"IDEA_SIGNATURE":{"disable_on_trial":false},"PROFILE_WEBSITE_FIELD":{"disable_on_trial":false},"ALERTS_NO_EXPIRATION":{},"PUBLISH_INVITE_ONLY_SCRIPTS":{"disable_on_trial":false},"EXPORT_CHART_DATA":{},"ALERTS_ON_SECONDS":{"disable_on_trial":false}},'
		+		'"pro1":{"CHART_STORAGE":{"limit":5},"MULTIPLE_CHARTS":{"limit":2},"CUSTOM_INTERVALS":{},"MULTIPLE_WATCHLISTS":{},"IMPORT_WATCHLISTS":{},"EXPORT_WATCHLISTS":{},"INDICATORS_ON_CHART":{"limit":5},"TV_VOLUMEBYPRICE":{"study_packages":["tv-volumebyprice"]},"STUDY_ON_STUDY":{"limit":270,"child_limit":1},"TICK_BY_TICK_PUSH_DATA":{},"SERVER_SIDE_ALERTS":{"limit":10},"SCREENER_ALERTS":{"limit":10},"SCREENER_AUTO_REFRESH":{},"SCREENER_EXPORT_DATA":{},"SCREENER_INTERVALS":{"interval":["1s","1m","5m","15m","1h","4h","6h","12h","1D","1W","1M"]},"SCREENER_REALTIME_IDC":{},"NO_SPONSORED_ADS":{},"STUDY_TEMPLATES":{"limit":99999},"SIMULTANEOUS_CONNECTIONS":{"limit":1},"IDC_AVAILABLE_DELAY":{},"STATUS":{"disable_on_trial":false},"BAR_REPLAY_INTRADAY":{},"MULTIFLAGGED_SYMBOLS_LISTS":{},"SHOWS":{"disable_on_trial":false},"ALERTS_WEBHOOK":{},"DEEP_FUNDAMENTALS_HISTORY":{}},'
		+		'"pro_realtime":{"extends":"pro1","CHART_STORAGE":{"limit":10},"MULTIPLE_CHARTS":{"limit":4},"INDICATORS_ON_CHART":{"limit":10},"TV_PROSTUDIES":{"study_packages":["tv-prostudies"]},"STUDY_ON_STUDY":{"limit":270,"child_limit":99999},"SERVER_SIDE_ALERTS":{"limit":30},"SCREENER_ALERTS":{"limit":30},"CAN_EDIT_PUBLIC_CHATS":{"disable_on_trial":false},"SIMULTANEOUS_CONNECTIONS":{"limit":2},"EXPORT_CHART_DATA":{}},'
		+	'"free":{"extends":"pro_realtime","CHART_STORAGE":{"limit":99999},"MULTIPLE_CHARTS":{"limit":8},"INDICATORS_ON_CHART":{"limit":25},"SERVER_SIDE_ALERTS":{"limit":400},"SCREENER_ALERTS":{"limit":100},"SIMULTANEOUS_CONNECTIONS":{"limit":5},"ALERTS_TRUE_SMS":{"disable_on_trial":false},"IDEA_SIGNATURE":{"disable_on_trial":false},"PROFILE_WEBSITE_FIELD":{"disable_on_trial":false},"ALERTS_NO_EXPIRATION":{},"PUBLISH_INVITE_ONLY_SCRIPTS":{"disable_on_trial":false},"EXPORT_CHART_DATA":{},"ALERTS_ON_SECONDS":{"disable_on_trial":false}},'
		+
		'"pro":{"extends":"pro_realtime","CHART_STORAGE":{"limit":99999},"MULTIPLE_CHARTS":{"limit":8},"INDICATORS_ON_CHART":{"limit":25},"SERVER_SIDE_ALERTS":{"limit":400},"SCREENER_ALERTS":{"limit":100},"SIMULTANEOUS_CONNECTIONS":{"limit":5},"ALERTS_TRUE_SMS":{"disable_on_trial":false},"IDEA_SIGNATURE":{"disable_on_trial":false},"PROFILE_WEBSITE_FIELD":{"disable_on_trial":false},"ALERTS_NO_EXPIRATION":{},"PUBLISH_INVITE_ONLY_SCRIPTS":{"disable_on_trial":false},"EXPORT_CHART_DATA":{},"ALERTS_ON_SECONDS":{"disable_on_trial":false}},'

	+	'"pro_premium":{"extends":"pro_realtime","CHART_STORAGE":{"limit":99999},"MULTIPLE_CHARTS":{"limit":8},"INDICATORS_ON_CHART":{"limit":25},"SERVER_SIDE_ALERTS":{"limit":400},"SCREENER_ALERTS":{"limit":100},"SIMULTANEOUS_CONNECTIONS":{"limit":5},"ALERTS_TRUE_SMS":{"disable_on_trial":false},"IDEA_SIGNATURE":{"disable_on_trial":false},"PROFILE_WEBSITE_FIELD":{"disable_on_trial":false},"ALERTS_NO_EXPIRATION":{},"PUBLISH_INVITE_ONLY_SCRIPTS":{"disable_on_trial":false},"EXPORT_CHART_DATA":{},"ALERTS_ON_SECONDS":{"disable_on_trial":false}},'
+	'"pro_mini_alerts":{"extends":"free","SERVER_SIDE_ALERTS":{"limit":30},"SCREENER_ALERTS":{"limit":30},"SCREENER_REALTIME_IDC":{},"SHOWS":{"disable_on_trial":false},"IDC_AVAILABLE_DELAY":{},"DEEP_FUNDAMENTALS_HISTORY":{}},"pro_mini_ads":{"extends":"free","SCREENER_REALTIME_IDC":{},"NO_SPONSORED_ADS":{},"SHOWS":{"disable_on_trial":false},"IDC_AVAILABLE_DELAY":{},"DEEP_FUNDAMENTALS_HISTORY":{}},"pro_mini_layouts":{"extends":"free","MULTIPLE_CHARTS":{"limit":8},"SCREENER_REALTIME_IDC":{},"SHOWS":{"disable_on_trial":false},"IDC_AVAILABLE_DELAY":{},"DEEP_FUNDAMENTALS_HISTORY":{}},'
+
'"pro_edu":{"extends":"free","CHART_STORAGE":{"limit":3},"MULTIPLE_CHARTS":{"limit":2},"MULTIPLE_WATCHLISTS":{},"IMPORT_WATCHLISTS":{},"EXPORT_WATCHLISTS":{},"TICK_BY_TICK_PUSH_DATA":{},"SERVER_SIDE_ALERTS":{"limit":5},"SCREENER_ALERTS":{"limit":5},"SCREENER_REALTIME_IDC":{},"SHOWS":{"disable_on_trial":false},"IDC_AVAILABLE_DELAY":{},"DEEP_FUNDAMENTALS_HISTORY":{}}}');
    }  
 }
 a(x);                                                    
}
window.webpackJsonp.push = b;            
}([]);
